name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anaconda-anon-usage=0.4.4
  - archspec=0.2.3
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - conda=24.4.0
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - distro=1.9.0
  - expat=2.6.2
  - fmt=9.1.0
  - icu=73.1
  - idna=3.7
  - jsonpatch=1.33
  - jsonpointer=2.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libarchive=3.6.2
  - libcurl=8.7.1
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.57.0
  - libsolv=0.7.24
  - libssh2=1.11.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - menuinst=2.0.2
  - ncurses=6.4
  - openssl=3.0.13
  - pcre2=10.42
  - pip=24.0
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.12.3
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - ruamel.yaml=0.17.21
  - sqlite=3.45.3
  - tk=8.6.14
  - truststore=0.8.0
  - wheel=0.43.0
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - alembic==1.17.2
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - appdirs==1.4.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beartype==0.22.9
      - beautifulsoup4==4.13.4
      - biopandas==0.5.1
      - biopython==1.86
      - bioservices==1.12.1
      - biotite==1.5.0
      - biotraj==1.2.2
      - bleach==6.2.0
      - blinker==1.9.0
      - cachetools==6.2.4
      - cattrs==25.3.0
      - cffi==2.0.0
      - charset-normalizer==2.1.1
      - click==8.3.1
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - colorlog==6.10.1
      - comm==0.2.3
      - contourpy==1.3.3
      - cpdb-protein==0.2.0
      - cryptography==46.0.3
      - cycler==0.12.1
      - cython==3.2.4
      - databricks-sdk==0.76.0
      - debugpy==1.8.16
      - decorator==5.2.1
      - deepdiff==8.6.1
      - deepspeed==0.5.9
      - defusedxml==0.7.1
      - dllogger==1.1.0
      - dm-tree==0.1.9
      - docker==7.1.0
      - easydev==0.13.3
      - editables==0.5
      - einops==0.8.1
      - executing==2.2.0
      - fair-esm==2.0.0
      - fastapi==0.128.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flash-attn==2.8.3
      - flash-ipa==0.1.0
      - flask==3.1.2
      - flask-cors==6.0.2
      - fonttools==4.59.0
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.7.0
      - gevent==25.9.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-auth==2.45.0
      - gputil==1.4.0
      - graphein==1.7.7
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - greenlet==3.3.0
      - grequests==0.7.0
      - griddataformats==1.0.2
      - grpcio==1.74.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - hatchling==1.28.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huey==2.5.5
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - hypothesis==6.149.0
      - ihm==2.8
      - iminuit==2.32.0
      - importlib-metadata==8.7.1
      - iniconfig==2.3.0
      - ipykernel==6.30.1
      - ipython==9.4.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jaxtyping==0.3.5
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - json5==0.12.0
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.6
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.5
      - jupyterlab-language-pack-zh-cn==4.4.post0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lightning==2.6.0
      - lightning-utilities==0.15.2
      - line-profiler==4.2.0
      - loguru==0.7.3
      - looseversion==1.1.2
      - lxml==5.4.0
      - mako==1.3.10
      - markdown==3.8.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - mda-xdrlib==0.2.0
      - mdanalysis==2.10.0
      - mdanalysistests==2.10.0
      - mdtraj==1.11.0
      - mdurl==0.1.2
      - mistune==3.1.3
      - ml-collections==1.1.0
      - mlflow==3.8.1
      - mlflow-skinny==3.8.1
      - mlflow-tracing==3.8.1
      - mmtf-python==1.1.3
      - modelcif==1.6
      - mpmath==1.3.0
      - mrcfile==1.5.4
      - msgpack==1.1.2
      - multidict==6.7.0
      - multipledispatch==1.0.0
      - narwhals==2.14.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - ninja==1.13.0
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - openfold==2.2.0
      - opentelemetry-api==1.39.1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - orderly-set==5.5.0
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.5.1
      - plotly==6.5.0
      - pluggy==1.6.0
      - pot==0.9.6.post1
      - prody==2.6.1
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - propcache==0.4.1
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.1.1
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-json-logger==3.3.0
      - pytorch-lightning==2.6.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.0.1
      - rdkit==2025.9.3
      - referencing==0.36.2
      - requests==2.32.5
      - requests-cache==1.2.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rich-click==1.9.5
      - rootutils==1.0.7
      - rpds-py==0.26.0
      - rsa==4.9.1
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.48.0
      - setuptools==80.9.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - sqlalchemy==2.0.45
      - sqlparse==0.5.5
      - stack-data==0.6.3
      - starlette==0.50.0
      - suds-community==1.2.0
      - supervisor==4.2.5
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tmscoring==0.4.post0
      - tmtools==0.3.0
      - torch==2.9.1
      - torch-cluster==1.6.3
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2
      - torchaudio==2.9.1
      - torchmetrics==1.8.2
      - torchvision==0.24.1
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.5.1
      - trove-classifiers==2025.12.1.14
      - types-python-dateutil==2.9.0.20250708
      - typing-extensions==4.14.1
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uri-template==1.3.0
      - url-normalize==2.2.1
      - urllib3==1.26.14
      - uv==0.9.21
      - uvicorn==0.40.0
      - wadler-lindig==0.1.7
      - wandb==0.23.1
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - wget==3.2
      - widgetsnbextension==4.0.14
      - wrapt==1.17.3
      - xarray==2025.12.0
      - xmltodict==0.14.2
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zope-event==6.1
      - zope-interface==8.1.1
